import "./globals.css";
import { DM_Sans } from "next/font/google";
import Header from '@/components/Header'
import Confirm from "@/components/Confirm";


const DMSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={DMSans.className}>
        <div className="layout flex">
          <div className="header w-[18%]  h-screen bg-primary">  <Header/></div>
          <div className="dynamicContent flex-grow-[1] px-[2.5rem] relative"> 
          {children}
           <Confirm/>
          </div>
          <div className="footer w-[27.6%]  h-screen bg-primary_light"></div>
        </div>
      </body>
    </html>
  );
}
