import "./globals.css";
import { lato, DMSans } from "@/font";
import LayoutMain from "@/components/LayoutMain";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${DMSans.variable} ${lato.variable}`}>
      {/* className="overflow-hidden" */}
      <body>
       <LayoutMain children = {children}/>
      </body>
    </html>
  );
}
