import {
  product1,
  product2,
  product3,
  product4,
  product5,
  phone1,
  phone2,
  phone3,
  phone4,
  phone5,
  accessories1,
  accessories2,
  accessories3,
  accessories4,
  accessories5,
  cable1,
  cable2,
  cable3,
  cable4,
  cable5,
  laptop1,
  laptop2,
  laptop3,
  laptop4,
  laptop5,
  adapter1,
  adapter2,
  adapter3,
  adapter4,
  adapter5,


} from "./image/index";

export const products = [
  {
    id: 1,
    productname: "iPhone 6S",
    desc: "A14 Bionic chip, 256 GB ROM",
    image:phone1,
    proid: 1,
    category: "phone",
  },
  {
    id: 2,
    productname: "Samsung Galaxy S21",
    desc: "Exynos 2100 chip, 128 GB ROM",
    image:phone2,
    proid: 2,
    category: "phone",
  },
  {
    id: 3,
    productname: "Google Pixel 6",
    desc: "Google Tensor chip, 512 GB ROM",
    image:phone3,
    proid: 3,
    category: "phone",
  },
  {
    id: 4,
    productname: "OnePlus 9 Pro",
    desc: "Snapdragon 888 chip, 256 GB ROM",
    image:phone4,
    proid: 4,
    category: "phone",
  },
  {
    id: 5,
    productname: "Sony Xperia 1 III",
    desc: "Snapdragon 888 chip, 256 GB ROM",
    image:phone5,
    proid: 5,
    category: "phone",
  },

  {
    id: 6,
    productname: "Fast Charger Cable",
    desc: "High-speed charging cable for iPhone and iPad, MFi certified, 6 feet in length.",
    proid: 23,
    image:cable1,
    category: "Cable",
  },
  {
    id: 7,
    productname: "Apple Lightning Cable",
    desc: "Genuine Apple charging cable for all Lightning devices, 3.3 feet long.",
    proid: 24,
    image:cable2,
    category: "Cable",
  },
  {
    id: 8,
    productname: "USB-C to Lightning Cable",
    desc: "",
    image:cable3,
    proid: 25,
    category: "Cable",
  },
  {
    id: 9,
    productname: "Braided iPhone Cable",
    desc: "Ultra-thin charging cable with a compact connector for easy storage, 2 feet long..",
    proid: 26,
    category: "Cable",
    image: cable4,
  },
  {
    id: 10,
    productname: "Slim Lightning Cable",
    desc: "Ultra-thin charging cable with a compact connector for easy storage, 2 feet long.",
    proid: 27,
    image: cable5,
    category: "Cable",
  },

  {
    id: 11,
    productname: "Lightning to USB Adapter",
    desc: "Connect your Lightning devices to USB accessories and peripherals. Compatible with iPhone and iPad.",
    proid: 32,
    category: "adapters",
    image: adapter1,
  },
  {
    id: 12,
    productname: "USB-C to Lightning Adapter",
    desc: "Convert USB-C ports to Lightning ports for charging and data transfer. Works with various devices.",
    proid: 33,
    category: "adapters",
    image: adapter2,
  },
  {
    id: 13,
    productname: "Audio Jack Adapter",
    desc: "3.5mm audio jack to Lightning adapter for connecting headphones to your iPhone or iPad.",
    proid: 34,
    category: "adapters",
    image: adapter3,
  },
  {
    id: 14,
    productname: "HDMI Adapter",
    desc: "HDMI to Lightning adapter for streaming content from your iPhone or iPad to your TV.",
    proid: 35,
    category: "adapters",
    image: adapter4,
  },
  {
    id: 15,
    productname: "Multi-Port Adapter",
    desc: "Versatile multi-port adapter with USB, HDMI, and SD card slots for your iPhone or iPad.",
    proid: 36,
    category: "adapters",
    image: adapter5,
  },
  {
    id: 16,
    productname: "UltraBook Pro X1",
    desc: "Powerful laptop with a high-resolution display, fast processor, and long battery life.",
    proid: 37,
    category: "Laptops",
    image: laptop1,
  },
  {
    id: 17,
    productname: "SlimBook S2",
    desc: "Thin and lightweight laptop with a sleek design, perfect for on-the-go professionals.",
    proid: 38,
    category: "Laptops",
    image: laptop2,
  },
  {
    id: 18,
    productname: "Gaming Beast Z2",
    desc: "High-performance gaming laptop with dedicated graphics and a fast refresh rate display.",
    proid: 39,
    category: "Laptops",
    image: laptop3,
  },
  {
    id: 19,
    productname: "BusinessBook Pro",
    desc: "Business-focused laptop with security features, robust performance, and a durable build.",
    proid: 40,
    category: "Laptops",
    image: laptop4,
  },
  {
    id: 20,
    productname: "Convertible FlexBook",
    desc: "2-in-1 laptop and tablet with a flexible hinge, touchscreen display, and stylus support.",
    proid: 41,
    category: "Laptops",
    image: laptop5,
  },
  {
    id: 21,
    productname: "Wireless Mouse",
    desc: "Ergonomic wireless mouse for comfortable use with your laptop or desktop computer.",
    proid: 42,
    category: "Accessories",
    image: accessories1,
  },
  {
    id: 22,
    productname: "Keyboard Cover",
    desc: "Protective keyboard cover made of silicone, compatible with various laptop models.",
    proid: 43,
    category: "Accessories",
    image: accessories2,
  },
  {
    id: 23,
    productname: "Laptop Stand",
    desc: "Adjustable laptop stand with multiple height settings for improved ergonomics.",
    proid: 44,
    category: "Accessories",
    image: accessories3,
  },
  {
    id: 24,
    productname: "External Hard Drive",
    desc: "High-capacity external hard drive for backing up your important files and data.",
    proid: 45,
    category: "Accessories",
    image: accessories4,
  },
  {
    id: 25,
    productname: "Headphone Adapter",
    desc: "3.5mm headphone to USB-C adapter for connecting headphones to devices without headphone jacks.",
    proid: 46,
    category: "Accessories",
    image: accessories5,
  },
];
